spring:
  application:
    name: eshop-one-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/goodsdetail?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 725810
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 1212
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

feign:
   hystrix:
       enabled: true


