spring:
  application:
    name: cacheservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goodsdetail?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 725810

server:
  port: 2345
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shop.learning.cacheEntity
