spring:
  application:
    name: eshop-systongbu-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 725810
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest


server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/